### ISSUE TITLE
incorporate star masking code from pizza cutter

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter-metadetect#5]
The stars will now be in the pizza file.

There is a PR on pizza cutter to remove the masking code, so would need to check out a previous version

**Comment by esheldon** [comment]
The star extension will be called `stars`

**Comment by esheldon** [comment]
actually better to do
```
import pizza_cutter.des_pizza_cutter import STARS_EXTNAME
```

**Comment by beckermr** [comment]
The code can go here: https://github.com/beckermr/pizza-cutter-metadetect/blob/main/pizza_cutter_metadetect/run_metadetect.py#L225

**Comment by beckermr** [comment]
We can put the gaia config in a subsection under this key in the main config: `pizza-cutter-preprocessing`
